apiVersion: v1
kind: ResourceQuota
metadata:
  name: rob-resource-quota
  namespace: rob
spec:
  hard:
    limits.cpu: "1000m"
    limits.memory: 2Gi
    requests.cpu: "2000m"
    requests.memory: 4Gi