apiVersion: apps/v1
kind: Deployment
metadata:
  name: octant
  namespace: {{ .Values.deployment.namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  minReadySeconds: {{ .Values.deployment.minReadySeconds | default 3 }}
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: octant
  template:
    metadata:
      labels:
        app: octant
    spec:
      containers:
      - name: octant
        image: "22ndtech/octant:{{ .Values.deployment.imageVersion }}"
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: {{ .Values.deployment.containerPort }}
          protocol: TCP
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
          requests:
            cpu: "250m"
            memory: "64Mi"
        volumeMounts:
          - name: kube-config
            mountPath: /.kube
            readOnly: true
      volumes:
      - name: kube-config
        secret:
          secretName: kube-config-admin