# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: octant.jaackdreality-com
#   namespace: default
#   annotations:
#     external-dns.alpha.kubernetes.io/hostname: octant.jaackdreality.com
#     kubernetes.io/ingress.class: nginx
#     kubernetes.io/tls-acme: "true"
#     cert-manager.io/cluster-issuer: letsencrypt-staging
# spec:
#   tls:
#     - secretName: letsencrypt
#       hosts:
#         - octant.jaackdreality.com
#   rules:
#     - host: octant.jaackdreality.com
#       http:
#         paths:
#           - backend:
#              service:
#               name: octant
#               port:
#                 number: {{ .Values.deployment.containerPort }}
#             path: /
#             pathType: ImplementationSpecific
#     - host: octant.jaackdreality.com
#       http:
#         paths:
#           - backend:
#              service:
#               name: octant
#               port:
#                 number: {{ .Values.deployment.containerPort }}
#             path: /
#             pathType: ImplementationSpecific
