apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    name: mongodb-pod
    app: todo-app

spec:
      containers:
      - image: mongo
        name: mongodb-container
        ports:
        - name: mongo
          containerPort: 27017

        volumeMounts:
          - name: mongo-storage
            mountPath: /data/db

      volumes:
          - name: mongo-storage
            hostPath:
              path: /data/db