apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
    name: node-service
    app: todo-app

spec:
  selector:
    name: node-pod
  type: NodePort
  ports:
   - name: http
     port: 3000
     targetPort: 3000
     protocol: TCP