apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
  labels:
    name: simple-deployment
    env: exp
spec:
  replicas: 3
  selector:
    matchLabels:
      name: simple-pod
  template:
    metadata:
      labels:
        name: simple-pod
    spec:
      containers:
      - name: simple-pod
        image: nginx
        ports:
        - containerPort: 80