apiVersion: v1
kind: Service
metadata:
  name: simple-service
  labels:
    name: simple-service
    env: exp
spec:
  selector:
    name: simple-pod
  type: NodePort
  ports:
    - port: 80
      name: http
      targetPort: 80
      protocol: TCP