---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "rob" to get, watch and list namespaces globally
kind: ClusterRoleBinding
metadata:
  name: rob-namespace-lister
subjects:
# You can specify more than one "subject"
- kind: User
  name: rob # "name" is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: namespace-lister # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "rob" to get, watch and list namespaces globally
kind: RoleBinding
metadata:
  name: rob-read-default
  namespace: default
subjects:
# You can specify more than one "subject"
- kind: User
  name: rob # "name" is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: view # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "rob" to get, watch and list namespaces globally
kind: RoleBinding
metadata:
  name: rob-read-flux-system
  namespace: flux-system
subjects:
# You can specify more than one "subject"
- kind: User
  name: rob # "name" is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: view # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "rob" to get, watch and list namespaces globally
kind: RoleBinding
metadata:
  name: rob-read-kube-system
  namespace: kube-system
subjects:
# You can specify more than one "subject"
- kind: User
  name: rob # "name" is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: view # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "rob" to get, watch and list namespaces globally
kind: RoleBinding
metadata:
  name: rob-read-ndtech
  namespace: ndtech
subjects:
# You can specify more than one "subject"
- kind: User
  name: rob # "name" is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: view # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "rob" to get, watch and list namespaces globally
kind: RoleBinding
metadata:
  name: rob-own-namespace-edit
  namespace: rob
subjects:
# You can specify more than one "subject"
- kind: User
  name: rob # "name" is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: edit # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io