FROM digitalocean/doctl:1.48.0
LABEL maintainer="Jeff@22ndtech.com"

ARG CONTEXT_PATH="/root"

ENV NDTECH_K8S_MODE ${NDTECH_K8S_MODE} \
  ENV RELATIVE_PROCESSING_PATH ${RELATIVE_PROCESSING_PATH} \
  ENV CONTEXT_PATH="${CONTEXT_PATH}" \
  ENV JX_NO_DELETE_TMP_DIR \
  ENV GITHUB_NDTECH_K8S_PIPELINE_EMAIL \
  ENV GITHUB_NDTECH_K8S_PIPELINE_TOKEN \
  ENV GITHUB_NDTECH_K8S_ADMIN_USERNAME \
  ENV GITHUB_NDTECH_K8S_ADMIN_TOKEN \
  ENV GITHUB_TOKEN="$GITHUB_NDTECH_K8S_ADMIN_TOKEN" \
  ENV HMAC_TOKEN="$GITHUB_NDTECH_K8S_PIPELINE_TOKEN" \
  ENV DIGITAL_OCEAN_INITIAL_TOKEN="$DIGITAL_OCEAN_INITIAL_TOKEN"

WORKDIR "${CONTEXT_PATH}"

RUN \
  # move doctl to the path
  mv /app/doctl /usr/local/bin \
  # install kubectl
  && cd "${CONTEXT_PATH}" \
  && curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl" \
  && mv kubectl /usr/local/bin \
  && chmod +x /usr/local/bin/kubectl \
  && apk add git \ 
  && apk add python3 \
  && python3 -m ensurepip \
  && pip3 install --upgrade pip \
  && pip3 install yq \
  # install jenkins x
  && curl -L "https://github.com/jenkins-x/jx/releases/download/$(curl --silent "https://github.com/jenkins-x/jx/releases/latest" | sed 's#.*tag/\(.*\)\".*#\1#')/jx-linux-amd64.tar.gz" | tar xzv "jx" \
  && mv jx /usr/local/bin \
  && curl -s https://toolkit.fluxcd.io/install.sh | sh

COPY . .
  
# neither ENTRYPOINT nor CMD can use the replacement syntax for some reason but it needs to match the context
ENTRYPOINT "/root/execute.sh"