---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: ndtech-node-api-staging-kaniko-1
  namespace: ndtech-staging
spec:
  serviceAccountName: tekton
  taskRef:
    name: build-docker-image-from-git-source
  params:
    - name: pathToDockerFile
      value: Dockerfile
    - name: pathToContext
      value: $(resources.inputs.docker-source.path) #configure: may change according to your source
  resources:
    inputs:
      - name: docker-source
        resourceRef:
          name: ndtech-node-api-git
    outputs:
      - name: builtImage
        resourceRef:
          name: ndtech-node-api-staging-image