---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: ndtech-node-api-staging-kaniko-1
  namespace: ndtech
spec:
  serviceAccountName: tekton-triggers-admin
  taskRef:
    name: build-docker-image
  params:
    - name: pathToDockerFile
      value: Dockerfile
    - name: pathToContext
      value: $(resources.inputs.source-repo.path) #configure: may change according to your source
  resources:
    inputs:
      - name: source-repo
        resourceRef:
          name: ndtech-node-api-git
    outputs:
      - name: builtImage
        resourceRef:
          name: ndtech-node-api-staging-image
# ---
# apiVersion: tekton.dev/v1beta1
# kind: TaskRun
# metadata:
#   name: ndtech-node-api-staging-kaniko-1
#   namespace: ndtech-staging
# spec:
#   taskRef:
#     name: kaniko
#   workspaces:
#   - name: source
#     emptyDir: {}
#   params:
#     - name: IMAGE
#       value: 22ndtech/ndtech-node-api:0.0.1
#     # - name: DOCKERFILE
#     #   value: ./Dockerfile
#     # - name: CONTEXT
#     #   value: git://github.com/22ndtech/ndtech-node-api/commit/21ee2041d7d9eaee43152d7be4e3bb6562b17f78
#     - name: EXTRA_ARGS
#       value: "--skip-tls-verify"
#     # - name: BUILDER_IMAGE
#     #   value: gcr.io/kaniko-project/executor@sha256:e36c9fa99279217c4bb8ee172819b441c3ca8ef946dc0e28b21721eefb2ba70a
#     # - name: CONTEXT
#     #   value: "git:github.com/22ndtech/ndtech-node-api/"
#     # - name: pathToContext
#     #   value: $(resources.inputs.docker-source.path)/
#     - name: CONTEXT
#       value: $(resources.inputs.docker-source.path)
#   resources:
#     inputs:
#       - name: docker-source
#         resourceRef:
#           name: skaffold-git
#     outputs:
#       - name: builtImage
#         resourceRef:
#           name: skaffold-image-leeroy-web