cat <<EOF | kubectl apply -f -
---
apiVersion: v1
kind: Secret
metadata:
  name: tekton-trow-secret
  namespace: ndtech-staging
  annotations:
    tekton.dev/docker-0: https://10.245.38.63:8000
type: kubernetes.io/basic-auth
stringData:
  username: $TROW_USERNAME
  password: $TROW_PASSWORD
---
EOF