apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: node-replica-set
  labels:
    name: node-replica-set
    app: todo-app

spec:
  replicas: 2
  selector:
    matchLabels:
      name: node-pod
  template:
    metadata:
      labels:
        name: node-pod
    spec:
      containers:
      - name: node-pod
        image: jeff22ndtech/simple-todo-app
        ports:
        - containerPort: 3000