apiVersion: "v1"
kind: Pod
metadata:
 name: simple-pod
 labels:
  name: simple-pod
  env: exp
spec:
 containers:
  - name: simple-web
    image: nginx
    ports:
     - containerPort: 80
       name: http
       protocol: TCP