# output "kubectl_config" {
#   description = "kubectl config as generated by the module."
#   value       = module.eks.kubeconfig
# }

output "region1" {
  description = "GKE Region"
  value       = local.region
}

output "cluster_name" {
  description = "Kubernetes Cluster Name"
  value       = local.cluster_name
}

# output "google_container_cluster-primary-name" {
#   description = "google_container_cluster.primary.name"
#   value = google_container_cluster.primary.name
# }

# output "google_container_cluster-primary-private_cluster_config-private_endpoint" {
#   description = "google_container_cluster.primary.private_cluster_config.private_endpoint"
#   value = google_container_cluster.primary.private_cluster_configprivate_endpoint
# }

# output "google_container_cluster-primary-private_cluster_config-public_endpoint" {
#   description = "google_container_cluster.primary.private_cluster_config.public_endpoint"
#   value = google_container_cluster.primary.private_cluster_config.public_endpoint
# }